# Generated by Django 4.2.30 on 2026-04-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('brand', models.CharField(max_length=255)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overdue_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='bills.route')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
