# Generated by Django 4.2.30 on 2026-04-13 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='bills.outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together={('name', 'route')},
        ),
    ]
