# Generated by Django 4.2.30 on 2026-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_invoice_and_cancelled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='bills_bill_status_aaa1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['assigned_to'], name='bills_bill_assigne_5670cb_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['assigned_to', 'status'], name='bills_bill_assigne_f34288_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['invoice_date'], name='bills_bill_invoice_0d73a6_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_at'], name='bills_bill_created_41cbb7_idx'),
        ),
    ]
