# Generated by Django 4.2.30 on 2026-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_invoicesequencesetting_party_printableinvoice_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printableinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='finalized', max_length=20),
        ),
        migrations.AlterField(
            model_name='printableinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
