# Generated by Django 4.2.30 on 2026-06-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_st_product_4a3e21_idx_products_st_product_2f7832_idx_and_more'),
        ('reports', '0009_alter_printableinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printableinvoiceitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from which stock was deducted for this invoice line item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.warehouse'),
        ),
    ]
