# Generated by Django 4.2.30 on 2026-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_printableinvoiceitem_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printableinvoice',
            name='invoice_date',
            field=models.DateField(db_index=True),
        ),
    ]
