# Generated by Django 4.2.30 on 2026-06-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stocktransfer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='products_st_product_2f7832_idx',
            old_name='products_st_product_4a3e21_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='products_st_created_792bf6_idx',
            old_name='products_st_created_8f2b14_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='products_st_source__859d2f_idx',
            old_name='products_st_source__b3c1d2_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='products_st_destina_e5a441_idx',
            old_name='products_st_dest__a7f3e1_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='products_st_product_ded2f9_idx',
            old_name='products_st_product_c8d2b1_idx',
        ),
    ]
