# Generated by Django 4.2.30 on 2026-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminotp',
            index=models.Index(fields=['user', 'used', 'expires_at'], name='users_admin_user_id_cdd7a4_idx'),
        ),
    ]
