# Generated by Django 4.2.30 on 2026-06-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_actor_username_ip_address'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_41600a_idx',
            old_name='core_auditl_actor_c3d1a2_idx',
        ),
    ]
